[chore|sde-backend] Docker notice.md added
eclipse-tractusx/managed-simple-data-exchanger-backend pull request #101
Opened 2024-02-22 09:54 UTC by adityagajbhiye9

## Description

- Docker notice.md added.

## Pre-review checks

Please ensure to do as many of the following checks as possible, before asking for committer review:

- [ ] DEPENDENCIES are up-to-date. [Dash license tool](https://github.com/eclipse/dash-licenses). Committers can open IP issues for restricted libs.
- [ ] [Copyright and license header](https://eclipse-tractusx.github.io/docs/release/trg-7/trg-7-02) are present on all affected files

2024-02-23 10:00 UTC, adkumar1 commented
Need to remove "_Notice for Docker image_" from README.md
& create a link in README.md referering DOCKER_NOTICE.md

2024-02-23 10:27 UTC, adkumar1 commented
Looks fine now

2024-02-23 10:27 UTC, adkumar1 approved these changes

2024-02-26 09:54 UTC, hzierer requested changes
- I think you have to adjust your workflow too to include the newly created file instead of the default README.
see the last line ( readme-filepath ... ) [here](https://eclipse-tractusx.github.io/docs/release/trg-4/trg-4-06#github-workflow-step)
- please rename the file to `notice.md` as stated in the TRG

2024-02-26 10:04 UTC, adityagajbhiye9 commented
@hzierer  As notice file already exit created the docker_notice.md file.

2024-02-26 10:09 UTC, hzierer commented
> @hzierer As notice file already exit created the docker_notice.md file.

yeah, sorry my bad. Haven't described it in detail enough. The "notice for docker" has to be in the same directory as the Docker file - so it is no problem to be named notice.md.

Sorry for any inconveniences caused.

2024-02-26 10:13 UTC, adityagajbhiye9 commented
@hzierer please review.

2024-02-26 10:14 UTC, adityagajbhiye9 commented
> > @hzierer As notice file already exit created the docker_notice.md file.
> 
> yeah, sorry my bad. Haven't described it in detail enough. The "notice for docker" has to be in the same directory as the Docker file - so it is no problem to be named notice.md.
> 
> Sorry for any inconveniences caused.

No worries :)

2024-02-26 10:40 UTC, adityagajbhiye9 commented on .github/workflows/dockerbuild.yaml
> +           readme-filepath: ./docker_notice.md
renamed it.

2024-02-26 13:14 UTC, hzierer approved these changes

2024-02-26 13:19 UTC, FaGru3n approved these changes
LGTM

2024-02-26 13:19 UTC, merged

2024-02-26 14:18 UTC, FaGru3n commented
sorry missed a upper case link in this PR that is not nessesary... so created a new one to fix but also don´t know your workflow how to change theese files... 

will close it... right now https://github.com/eclipse-tractusx/managed-simple-data-exchanger-backend/pull/105