[feat|sde-backend] : added policy controller for policy management.
eclipse-tractusx/managed-simple-data-exchanger-backend pull request #110
Opened 2024-03-26 09:28 UTC by ChetanT-System

## Description

### Added
- Added Policy Controller for policy management.

## Pre-review checks

Please ensure to do as many of the following checks as possible, before asking for committer review:

- [x] DEPENDENCIES are up-to-date. [Dash license tool](https://github.com/eclipse/dash-licenses). Committers can open IP issues for restricted libs.
- [x] [Copyright and license header](https://eclipse-tractusx.github.io/docs/release/trg-7/trg-7-02) are present on all affected files

2024-03-27 09:38 UTC, sachinargade123 approved these changes
LGTM

2024-03-28 05:59 UTC, adityagajbhiye9 requested changes
Please check comment.

2024-03-28 05:59 UTC, adityagajbhiye9 commented on modules/sde-core/src/main/java/org/eclipse/tractusx/sde/core/utils/ListToStringConverter.java
@ChetanT-System Please check copyright header, It should 2022-2024.

2024-03-28 06:37 UTC, adityagajbhiye9 approved these changes
LGTM

2024-04-01 07:32 UTC, adityagajbhiye9 commented
@almadigabor please approve and merge PR.

2024-04-01 08:04 UTC, adityagajbhiye9 commented
@tomaszbarwicki  Please review and merge.

2024-04-04 07:10 UTC, almadigabor approved these changes

2024-04-04 07:12 UTC, adityagajbhiye9 commented
Please merge.

2024-04-04 07:31 UTC, almadigabor commented
Hey! Please run the dash-tool again to check for dependencies changes. I ran it locally and seemed to be out of date. I would also suggest implementing the dependencies workflow to have an automated check on each PR like [here](https://github.com/eclipse-tractusx/portal-backend/blob/main/.github/workflows/dependencies.yaml).

2024-04-04 07:55 UTC, almadigabor commented
[Here](https://github.com/eclipse-tractusx/managed-simple-data-exchanger-backend/actions/runs/8551116115/job/23429436330?pr=110#step:9:9) you can see why the dependencies workflow failed. And also an updated file is attached to the workflow run as artefact that you can download to review and commit [here](https://github.com/eclipse-tractusx/managed-simple-data-exchanger-backend/actions/runs/8551116115?pr=110).

2024-04-04 10:11 UTC, ChetanT-System commented
@almadigabor  We have updated version in pom.xml file for dependencies check and also added workflow. Please review and merge again.

2024-04-04 10:13 UTC, merged